version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: trending_db
    environment:
      POSTGRES_DB: trending_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/database.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
